stages:
  get-features:
    cmd: python3 scripts/feature_engineering/get_features.py data/raw/
    deps:
    - data/raw/
    - scripts/feature_engineering/get_features.py
    outs:
    - data/features
  data-prep:
    cmd: python3 scripts/feature_engineering/data_preprocessing.py data/features/
    deps:
    - data/features/
    - scripts/feature_engineering/data_preprocessing.py
    outs:
    - data/prepared
  train:
    cmd: python3 scripts/model_scripts/model_preparation.py data/prepared/train.csv model.pkl
    deps:
    - data/prepared/train.csv
    - scripts/model_scripts/model_preparation.py
    params:
    - train.seed
    - train.iters
    outs:
    - models/model.pkl
  evaluate:
    cmd: python3 scripts/model_scripts/evaluate.py data/prepared/test.csv models/model.pkl
    deps:
    - data/prepared/test.csv
    - models/model.pkl
    - scripts/model_scripts/evaluate.py
    metrics:
    - evaluate.json:
        cache: false